version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: cms_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/cms
      SECRET_KEY: mysecretkey12345 
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ALGORITHM: HS256
    ports:
      - "8000:8000"
